### PR TITLE
Development Merge into Master

### PR DESCRIPTION
**Pull request by Rhelli**
PR for TSEs for code review

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @Rhelli,

### Amazing job! Clean code and an almost perfect clone. :+1: 

Just one thing, let's get rid of the horizontal scroll bar, it has to do with the `aside` styling. Refer to the image below:

hor


**Kindly submit for another code review once this issue has been fixed.** _Happy coding. :tada:_

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @Rhelli :wave: 

Nice job getting rid of the horizontal scroll bar :+1:. Please let's also swiftly fix the issues listed below. _I am sorry we missed it initally_

- [x]  Files not related to the project should not be committed and added to .gitignore (e.g. .vscode)
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.
https://github.com/Rhelli/Apple-Clone/blob/4ede4e0ebc7cefa782556cd13ff53f85da33f206/CSS/apple.css#L60

**Please submit another code review request after fixing those issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by ebukaume — APPROVED** [review]
## Approved! :champagne: 

Good job @Rhelli. **You can now go ahead and merge this branch**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by Rhelli** [comment]
@ebukaume @suretrust  No worries about the hidden errors. Thanks very much for the code reviews guys! Have a good weekend.

**Pull request merged**
